;/*FB_PKG_DELIM*/

__d("CometMarketplaceComponentLoggingContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b={metadata:null};c=a.createContext(b);g["default"]=c}),98);
__d("ProductTagPostClickFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1744228");b=d("FalcoLoggerInternal").create("product_tag_post_click",a);e=b;g["default"]=e}),98);
__d("CometProductTagLoggingUtils",["ProductTagPostClickFalcoEvent","requireDeferred"],(function(a,b,c,d,e,f,g){"use strict";var h=c("requireDeferred")("CommerceStorefrontImpressionFalcoEvent").__setRef("CometProductTagLoggingUtils"),i=c("requireDeferred")("CommerceTabFeedImpressionFalcoEvent").__setRef("CometProductTagLoggingUtils"),j="product_tag_on_";a=function(a,b,d,e,f,g){c("ProductTagPostClickFalcoEvent").log(function(){return{ad_id:a,component:b,funnel_id:d,marketplace_surface:e,post_id:f,referral_code:g}})};b=function(a,b,c,d,e,f,g,l,m){d=k(f,d);var n=d.analyticsPage,o=d.isPageFeed,p=d.isTabFeed,q=d.isTimeline,r=d.surface,s=j+((d=(d=r)!=null?d:f)!=null?d:"")+"_"+a;d=b!=null;if(n!=null)if(p)i.onReady(function(b){b.log(function(){var b;return{analytics_component:g,analytics_destination_page:e,analytics_feed_type:n==="home_feed"?"newsfeed":"unknown",analytics_module:l,analytics_page:n,content_id:a,legacy_referral_code:s,legacy_surface:(b=(b=r)!=null?b:f)!=null?b:"",legacy_ui_component:m,referral_surface:"unknown",shopping_session_id:""}})});else if(o||d&&q){var t={analytics_feed_type:o?"page":"profile",analytics_module:l,analytics_page:n,content_id:a,page_id:c,referral_surface:"unknown",shopping_session_id:""};h.onReady(function(a){b==null?a.log(function(){return babelHelpers["extends"]({},t)}):a.log(function(){return babelHelpers["extends"]({profile_id:b},t)})})}};d=function(a){var b;a==="AYMTNotificationChannel"?b="aymt_retro_tag_jewel":a==="AYMTEmailChannel"?b="aymt_retro_tag_email":a==="AYMTPageAdminMegaphoneV2Channel"||a==="AYMTPageAdminMegaphoneChannel"?b="aymt_retro_tag_megaphone":a==="AYMTUnknownChannel"&&(b="aymt_unknown_channel");return b};e=function(a,b,c,d){switch(a){case"home_feed":case"posts_feed":if(b===1&&c)return"product_details";else if(d)return"video_fullscreen";else return"photo_fullscreen";case"video_feed":return"video_fullscreen";default:return"unknown"}};var k=function(a,b){var c=null,d=null,e=!1,f=!1,g=!1;switch(a){case"NEWSFEED":c="home_feed";d="newsfeed";e=!0;break;case"PAGE_TIMELINE":f=!0;c="posts_feed";d="pages_feed";break;case"TIMELINE":g=!0;c="posts_feed";d="pages_feed";break;default:(a==null?void 0:a.includes("VIDEO"))||b==="video_home"?(c="video_feed",d="video_home",e=!0):(a==null?void 0:a.includes("GROUP"))&&(c=null,d="group_mall")}return{analyticsPage:c,isPageFeed:f,isTabFeed:e,isTimeline:g,surface:(a=d)!=null?a:b}};g.logProductTagPostClick=a;g.logImpressionEventForNewsFeedAndStorefront=b;g.getAYMTChannelName=d;g.getAnalyticsDestinationPage=e;g.getSurface=k}),98);
__d("CometProductTagReferralCodeContext",["react"],(function(a,b,c,d,e,f,g){"use strict";var h;a=h||d("react");b=a.createContext(null);g["default"]=b}),98);
__d("CommercePdpProductTagClickFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1743406");b=d("FalcoLoggerInternal").create("commerce_pdp_product_tag_click",a);e=b;g["default"]=e}),98);
__d("CommerceStorefrontImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("3157");b=d("FalcoLoggerInternal").create("commerce_storefront_impression",a);e=b;g["default"]=e}),98);
__d("CommerceTabFeedClickFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("1878");b=d("FalcoLoggerInternal").create("commerce_tab_feed_click",a);e=b;g["default"]=e}),98);
__d("CommerceTabFeedImpressionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("2315");b=d("FalcoLoggerInternal").create("commerce_tab_feed_impression",a);e=b;g["default"]=e}),98);
__d("XCometCommerceProductItemControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/commerce/products/{?slug}/{listing_id}/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);